version: '3'

services:
  app:
    image: lab-agent
    deploy:
      replicas: 3
    ports:
      - "8081-8090:5000"
      - "3300-3310:3306"
  ansible:
    build:
      context: ./task2
    volumes:
      - ./task2/playbooks:/playbooks
      - ./task2/inventory:/inventory
      - ./task2/ansible.cfg:/etc/ansible/ansible.cfg
    depends_on:
      - app
    ports:
      - "8080:8080"
    expose:
      - 5000
